name: SymbCompCC
version: "1.4.0"
license: "GPL-2.0-or-later"
date: 2026-08-14
description: |
    Computing with parametrised presentations for p-groups of fixed coclass

authors:
    - name: Dörte Feichtenschlager
      url: mailto:d.feichtenschlager@tu-braunschweig.de

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.7"

needed-pkgs:
    - name: "polycyclic"
      version: ">= 2.11"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/SymbCompCC/
readme: README
packageinfo: https://gap-packages.github.io/SymbCompCC/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/SymbCompCC/releases/download/v1.4.0/SymbCompCC-1.4.0.tar.gz

abstract: |
    The <span class="pkgname">SymbCompCC</span> package computes with parametrised presentations for finite p-groups of fixed coclass.

status: accepted
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    parametrised presentations for p-groups of fixed coclass and calculations with these.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Fei26</span>]   <b class='BibAuthor'>Feichtenschlager, D.</b>,
     <i class='BibTitle'>SymbCompCC, Computing with parametrised presentations for p-groups of fixed coclass,
             Version 1.4.0</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/SymbCompCC/">https://gap-packages.github.io/SymbCompCC/</a></span>.
    </p>
    

bibtex: |
    @misc{ SymbCompCC,
      author =           {Feichtenschlager, D.},
      title =            {{SymbCompCC},     {Computing     with     parametrised
                          presentations for p\texttt{\symbol{45}}groups of fixed
                          coclass}, {V}ersion 1.4.0},
      month =            {Aug},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href     {https://gap-packages.github.io/SymbCompCC/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{SymbCompCC/}}},
      keywords =         {parametrised             presentations             for
                          p\texttt{\symbol{45}}groups   of   fixed  coclass  and
                          calculations with these},
      printedkey =       {Fei26}
    }

