name: SymbCompCC
version: 1.3.2
date: 2022-02-10
description: |
    Computing with parametrised presentations for p-groups of fixed coclass

authors:
    - name: Dörte Feichtenschlager
      url: mailto:d.feichtenschlager@tu-braunschweig.de

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.7"

needed-pkgs:
    - name: "polycyclic"
      version: ">= 2.11"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/SymbCompCC/
readme: README
packageinfo: https://gap-packages.github.io/SymbCompCC/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/SymbCompCC/releases/download/v1.3.2/SymbCompCC-1.3.2.tar.gz

abstract: |
    The <span class="pkgname">SymbCompCC</span> package computes with parametrised presentations for finite p-groups of fixed coclass.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
