name: SymbCompCC
version: "1.3.2"
license: "GPL-2.0-or-later"
date: 2022-02-10
description: |
    Computing with parametrised presentations for p-groups of fixed coclass

authors:
    - name: Dörte Feichtenschlager
      url: mailto:d.feichtenschlager@tu-braunschweig.de

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.7"

needed-pkgs:
    - name: "polycyclic"
      version: ">= 2.11"
      url: "https://gap-packages.github.io/polycyclic/"

www: https://gap-packages.github.io/SymbCompCC/
readme: README
packageinfo: https://gap-packages.github.io/SymbCompCC/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/SymbCompCC/releases/download/v1.3.2/SymbCompCC-1.3.2.tar.gz

abstract: |
    The <span class="pkgname">SymbCompCC</span> package computes with parametrised presentations for finite p-groups of fixed coclass.

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    parametrised presentations for p-groups of fixed coclass and calculations with these.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>FT22</span>]   <b class='BibAuthor'>Feichtenschlager, D. and GAP Team, T.</b>,
     <i class='BibTitle'>SymbCompCC, Computing with parametrised presentations for p-groups of fixed coclass,
             Version 1.3.2</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/SymbCompCC/">https://gap-packages.github.io/SymbCompCC/</a></span>.
    </p>
    

bibtex: |
    @misc{ SymbCompCC1.3.2,
      author =           {Feichtenschlager, D. and GAP Team, T.},
      title =            {{SymbCompCC},      Computing     with     parametrised
                          presentations for p-groups of fixed coclass, {V}ersion
                          1.3.2},
      month =            {Feb},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href     {https://gap-packages.github.io/SymbCompCC/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{SymbCompCC/}}},
      keywords =         {parametrised   presentations  for  p-groups  of  fixed
                          coclass and calculations with these},
      printedkey =       {FT22}
    }

